# Generated by Django 6.0.3 on 2026-04-08 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
