# Generated by Django 6.0.3 on 2026-04-22 09:35

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_create_at_book_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='books.book')),
            ],
        ),
    ]
