# Generated by Django 6.0.3 on 2026-04-23 13:16

import books.validators
import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_bookimage'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='member.member'),
        ),
        migrations.AlterField(
            model_name='bookimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[books.validators.validate_file_size], verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
