# Generated by Django 6.0.3 on 2026-04-24 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_borrowrecord_member_alter_bookimage_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowRecord',
        ),
    ]
